### PR TITLE
Add exercise for nvidia-talk

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Here is a first draft for the exercise.
Let me know what  you think @stavros11 @igres26

### CODE REVIEW

**Comment by stavros11** [comment]
Thanks @andrea-pasquale, looks good to me. I have the following comments.

* In functions.py will only contain a single function for plotting, how about we just define it directly in the notebook, eg. in one of the first cells? This may make distributing it easier as we only need to send a single file and not worry about imports which may break if someone messes up the directories.
* I like the example of finding the 11...1 state as it is very simple and scalable, but maybe we could include a more useful example at the end of the tutorial, after the performance comparisons. @igres26 could have some ideas, otherwise we can also use the exact cover or 3SAT problems we already have in qibo examples.
* Regarding the hands-on tutorial, are we going to use the notebooks that are already on main, or are you planning to create a new one based on them?

**Comment by andrea-pasquale** [comment]
> Thanks @andrea-pasquale, looks good to me. I have the following comments.
> 
> * In functions.py will only contain a single function for plotting, how about we just define it directly in the notebook, eg. in one of the first cells? This may make distributing it easier as we only need to send a single file and not worry about imports which may break if someone messes up the directories.
> * I like the example of finding the 11...1 state as it is very simple and scalable, but maybe we could include a more useful example at the end of the tutorial, after the performance comparisons. @igres26 could have some ideas, otherwise we can also use the exact cover or 3SAT problems we already have in qibo examples.
> * Regarding the hands-on tutorial, are we going to use the notebooks that are already on main, or are you planning to create a new one based on them?

Thanks for the review.



> * In functions.py will only contain a single function for plotting, how about we just define it directly in the notebook, eg. in one of the first cells? This may make distributing it easier as we only need to send a single file and not worry about imports which may break if someone messes up the directories.

Fixed.



> * I like the example of finding the 11...1 state as it is very simple and scalable, but maybe we could include a more useful example at the end of the tutorial, after the performance comparisons. @igres26 could have some ideas, otherwise we can also use the exact cover or 3SAT problems we already have in qibo examples.

Yeah, probably we could. For the time being if you agree and would like to send them this first version and we can say that we will send an updated one later.


> * Regarding the hands-on tutorial, are we going to use the notebooks that are already on main, or are you planning to create a new one based on them?

Probably I will not touch them. If you want, since you are covering that part, feel free to edit them. Probably we need to add something related to the method `controlled_by`. 

Let me know if this version of the notebook (after removing the file functions.py works for you) so that we can already merge to main.

**Comment by stavros11** [comment]
> Let me know if this version of the notebook (after removing the file functions.py works for you) so that we can already merge to main.

Thanks for the updates, yes it works for me, including the GPU backends, so it should be fine to merge. The only potential issue is that in performance comparisons we probably need to go to >20 qubits to see the GPU performing better, but there is nothing we can do about this, they need to adjust the qubit range according to their resources.

> Probably I will not touch them. If you want, since you are covering that part, feel free to edit them. Probably we need to add something related to the method `controlled_by`.

So are you planning to send them as they are or are you only sending the exercise for now? Since the tutorial time is 30 minutes, I would probably just create a single notebook with the most important pieces from the existing ones and include the `controlled_by`. I can do this.

**Comment by andrea-pasquale** [comment]
Only the exercise for now. Since it is the only thing that they need to run on their machines. At this point I will do it tomorrow.

**Comment by andrea-pasquale** [comment]
I agree with the single notebook for the tutorial.
By the way, do you think that I should also in the notebook a few lines in order to install cupy / nvidia?
Or should I just tell them by email @stavros11 ?

**Comment by stavros11** [comment]
> By the way, do you think that I should also in the notebook a few lines in order to install cupy / nvidia? Or should I just tell them by email @stavros11 ?

Maybe we could add a link to the installation instructions in [qibo docs](https://qibo.readthedocs.io/en/stable/getting-started/installation.html#id1) in the notebook or the email. I believe the docs are clear regarding the GPU dependencies.

**Comment by andrea-pasquale** [comment]
@stavros11 @igres26 here is the (semi) final version

@stavros11 let me know if everything works

**Review by stavros11 — APPROVED** [review]
Thanks, looks good to me and works.

**Pull request merged**
